### ISSUE TITLE
1480. Running Sum of 1d Array [LeetCode]

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2021#1]
Given an array nums. We define a running sum of an array as runningSum[i] = sum(nums[0]…nums[i]).

Return the running sum of nums.

Example 1:

Input: nums = [1,2,3,4]
Output: [1,3,6,10]
Explanation: Running sum is obtained as follows: [1, 1+2, 1+2+3, 1+2+3+4].

**Comment by draja54** [comment]
Can I pick this up?

**Comment by Hussain6** [comment]
Can you assign this to me and can I do this in cpp?
