### ISSUE TITLE
Adding problems

### ISSUE THREAD

**Issue by SrihariTadala** [prog-harsh/Hacktoberfest2021#30]
I would like to solve problems in this platform
 
I want to work on this issue @kirantodupunoori @atrievel @DavidMaged171 @alifsiregar @RgnDunes 

I am currently preparing for my intern preparations and it would help me a lot , please do the needful and assign me this repo to do

**Comment by Karthiks08** [comment]
I would like to solve problems in this platform

I want to work on this issue @prog-harsh 

I am currently preparing for my intern preparations and it would help me a lot , please do the needful and assign me this repo to do

**Comment by SrihariTadala** [comment]
I would like to solve problems in this platform

I want to work on this issue @prog-harsh 

I am currently preparing for my intern preparations and it would help me a lot , please do the needful and assign me this repo to do
