### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2021#6]
Given an array nums of size n, return the majority element.

The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

Example 1:

Input: nums = [3,2,3]
Output: 3

**Comment by ArchanJS** [comment]
can I get assigned?

**Comment by ArchanJS** [comment]
Hey, @prog-harsh  I have made a PR. Please review that. Thank you in advane. :)
